[project]
name = "number-guessing-game"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.43.1",
]

[tool.uv.workspace]
members = ["growth-mindset-challange_data-sweeper"]
